spring:
  application:
    name: shoppal

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/shoppal
    username: franklin
    password: leedbpa22wd
    driver-class-name: org.postgresql.Driver


    
